version: 2
jobs:
  build:
    working_directory: ~/sms-management-system
    docker: 
      - image: node:11.10.0
        environment:
          DB_USERNAME: postgres
          DB_DIALECT: "postgres"
          DB_NAME: "sms-api"
          PORT: 9000

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 
          POSTGRES_DB: sms-api
  
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: npm update && npm install && npm rebuild node-sassc
    - run:
        name: Run  tests
        command: npm run test:migrate && npm run test:seed && npm run test:coverage
    - run:
        name: Push Test coverage to Coveralls
        command: coveralls < coverage/lcov.info
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
    