version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker: 
      - image: node:11.10.0
        environment:
          DB_USERNAME: root
          DB_DIALECT: "postgres"
          TEST_DB_NAME: "circle-test_test"
          PORT: 9000

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: 
          POSTGRES_DB: circle-test_test

    steps:
    - checkout
    - run:
        name: Install dependencies
        command: npm install
    - run:
        name: Run  tests
        command: npm run test:coverage
    - run:
        name: Push Test coverage to Coveralls
        command: coveralls < coverage/lcov.info
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
    